services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app  # Монтируем корневую директорию проекта в контейнер
    working_dir: /app  # Устанавливаем рабочую директорию
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery
    command: celery -A backend worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - .:/app  # Монтируем корневую директорию проекта
    working_dir: /app  # Устанавливаем рабочую директорию
