name: Django Deploy

on:
  push:
    branches:
      - main  # Deploy on pushes to the 'main' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'  # Specify your desired Python version

      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Collect static files
        run: |
          source venv/bin/activate
          python manage.py collectstatic --noinput

      - name: Migrate database
        run: |
          source venv/bin/activate
          python manage.py migrate

      - name: Deploy to server (replace with your deployment method)
        # Example: Deploy to a server using SSH
        uses: appleboy/scp-action@v0.2.1
          with:
            host: ${{ vars.SERVER_HOST }}
            username: ${{ vars.SERVER_USER }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            source: home/c/cl17008/deer/
            target: home/c/cl17008/deer/public_html

      - name: Restart server (replace with your server restart command)
        # Example: Restart Gunicorn server with systemd
        run: |
          ssh ${{ vars.SERVER_USER }}@${{ vars.SERVER_HOST }} 'sudo systemctl restart gunicorn'