name: Deploy Django Project

on:
  push:
    branches:
      - main  # Триггер только на пуши в ветку main

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
      # 1. Проверка репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Установка Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Версия Python

      # 3. Установка зависимостей
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Сбор статических файлов
      - name: Collect static files
        run: |
          python manage.py collectstatic --noinput

      # 5. Подключение к серверу и деплой
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 21
          script: |
            cd /home/cl17008/deer/public_html
            git pull origin main
            source /home/cl17008/deer/venv/bin/activate
            pip install -r requirements.txt
            python manage.py migrate
            python manage.py collectstatic --noinput
            systemctl restart your-django-app