name: Django Deploy

on:
  push:
    branches:
      - main  # Триггер на пуши в ветку 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Collect static files
        run: |
          source venv/bin/activate
          python manage.py collectstatic --noinput

      - name: Migrate database
        run: |
          source venv/bin/activate
          python manage.py migrate  # Миграция базы данных

      - name: Deploy to server
        uses: invi5H/ssh-action@v1.0.0
        with:
          SSH_HOST: ${{ secrets.SERVER_HOST }}
          SSH_USER: ${{ secrets.SERVER_USER }}
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/c/cl17008/deer/public_html
            git pull origin main  # Pull the latest code
            source venv/bin/activate  # Activate your virtual environment
            python manage.py migrate  # Run migrations
            python manage.py collectstatic --noinput

