name: Django Deploy

on:
  push:
    branches:
      - main  # Триггер на пуши в ветку 'main'

jobs:
  

  build-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.SERVER_HOST }}
          USER: ${{ secrets.SERVER_USER }}
        run: |
          echo "$SSH_PRIVATE_KEY" > ssh_key
          chmod 600 ssh_key
          ssh -T -o StrictHostKeyChecking=no -i ssh_key $USER@$HOST << EOF
          cd deer
          source venv/bin/activate
          cd public_html
          git pull origin main
          pip install -r requirements.txt
          export OPENBLAS_NUM_THREADS=4
          python manage.py makemigrations
          python manage.py migrate
          python manage.py collectstatic --noinput
          EOF