name: Django CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu:22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
        cd /home/c/cl17008/deer
        git pull origin main
        # Зависимости, миграции и рестарт сервера, если нужно:
        source venv/bin/activate
        pip install -r requirements.txt
        python manage.py migrate
        systemctl restart your-service
        EOF
